export const blogData = [
  {
    id: 1,
    img: "./assets/media/blog/image-01.jpg",
    title: "The 9-to-5 workday doesn’t work anymore",
    cate: "Design",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 2,
    img: "./assets/media/blog/news-02.jpg",
    title: "Cards on the table: 3 ways to spot a transparent company",
    cate: "Business",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 3,
    img: "./assets/media/blog/news-03.jpg",
    title: "Jobtex Announces Awards Criteria for the Best Places to Work 2023",
    cate: "Design",
    author: "Themeflat",
    time: "2 days ago",
  },

  {
    id: 4,
    img: "./assets/media/blog/image-17.jpg",
    cate: "Development",
    title: "How Does Writing Influence Your Personal Brand?",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 5,
    img: "./assets/media/blog/image-15.jpg",
    cate: "Graphic Design",
    title: "How To Write Content About Your Photographs",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 6,
    img: "./assets/media/blog/image-17.jpg",
    cate: "Content Marketing Design",
    title:
      "Where To Grow Your Business As A Photographer: Site Or Social Media?",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 7,
    img: "./assets/media/blog/image-18.jpg",
    cate: "Business",
    title: "Caring Is The New Marketing",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 8,
    img: "./assets/media/blog/image-19.jpg",
    cate: "Development",
    title: "Travelling As A Way Of Self-Discovery And Progress",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 9,
    img: "./assets/media/blog/image-20.jpg",
    cate: "Graphic Design",
    title: "Where To Grow Your Business As A Photographer",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 10,
    img: "./assets/media/blog/image-21.jpg",
    cate: "Graphic Design",
    title: "How To Choose The Right Customer",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 11,
    img: "./assets/media/blog/image-22.jpg",
    cate: "Graphic Design",
    title: "Start A Blog To Reach Your Creative Peak",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },
  {
    id: 12,
    img: "/assets/media/blog/image-23.jpg",
    cate: "Graphic Design",
    title: "Starting Your Traveling Blog With Vasco",
    author: "Themeflat",
    time: "2 days ago",
    text: "The jobs report soundly beat expectations, with job gains broadly spread across the economy and about 60% higher…",
  },

  {
    id: 13,
    img: "./assets/media/blog/image-06.jpg",
    cate: "Development",
    title: "How to make the most of your virtual admissions interview",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 14,
    img: "./assets/media/blog/image-09.jpg",
    cate: "Development",
    title: "Jobtex is named a top HR product in G2’s 2022 Best Software Awards",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 15,
    img: "./assets/media/blog/image-12.jpg",
    cate: "Development",
    title: "5 tips to create an ATS-friendly resume for post-grads",
    author: "Themeflat",
    time: "2 days ago",
  },

  {
    id: 16,
    img: "./assets/media/blog/image-07.jpg",
    cate: "Development",
    title: "Jobtex partners with SAP and is available via the SAP® Store",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 17,
    img: "./assets/media/blog/image-10.jpg",
    cate: "Development",
    title: "Jobtex is number one for ten consecutive quarters!",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 18,
    img: "./assets/media/blog/image-11.jpg",
    cate: "Development",
    title: "20 HR Podcasts for Human Resources Professionals",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 19,
    img: "./assets/media/blog/image-13.jpg",
    cate: "Development",
    title: "8 Steps You’re Missing Before Booking Your Demo",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 20,
    img: "./assets/media/blog/image-08.jpg",
    cate: "Development",
    title: "The Fight Against Academic Burnout",
    author: "Themeflat",
    time: "2 days ago",
  },
  {
    id: 21,
    img: "./assets/media/blog/image-14.jpg",
    cate: "Development",
    title: "16 Must-Read Human Resource Books in 2022",
    author: "Themeflat",
    time: "2 days ago",
  },
];
export const dataCards01 = [
  {
    title: "Blog 1",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-1.jpg",
    alt_text: "Blog Image 1",
  },
  {
    title: "Blog 2",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-2.jpg",
    alt_text: "Blog Image 2",
  },
  {
    title: "Blog 3",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-3.jpg",
    alt_text: "Blog Image 3",
  },
  {
    title: "Blog 4",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-4.jpg",
    alt_text: "Blog Image 4",
  },
  {
    title: "Blog 5",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-5.jpg",
    alt_text: "Blog Image 5",
  },
  {
    title: "Blog 6",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-6.jpg",
    alt_text: "Blog Image 6",
  },
  {
    title: "Blog 7",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-7.jpg",
    alt_text: "Blog Image 7",
  },
  {
    title: "Blog 8",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-8.jpg",
    alt_text: "Blog Image 8",
  },
  {
    title: "Blog 9",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent in mauris eu tortor porttitor accumsan.",
    link_url: "#",
    blog_image: "./assets/media/cards01/blog-image-9.jpg",
    alt_text: "Blog Image 9",
  },
];

export const dataCards02 = [
  {
    card_image: "./assets/media/cards02/card-1.png",
    alt_text: "Card Image 1",
    title: "Use a pre-integrated platform",
    description:
      "Explore our directory to find out-of-the-box solutions that connect with Stripe, such asSquarespaceand Lightspeed.",
    link_text: "Set Directory",
    link_url: "#",
  },
  {
    card_image: "./assets/media/cards02/card-2.png",
    alt_text: "Card Image 2",
    title: "Build with Stripe-certified experts",
    description:
      "Work with a Stripe consulting partner that can integrate and deploy Stripe solutions for you.",
    link_text: "Find Experts",
    link_url: "#",
  },
  {
    card_image: "./assets/media/cards02/card-3.png",
    alt_text: "Card Image 3",
    title: "Try our no-code products",
    description:
      "Create an invoice or share a payment link directly from your Dashboard to start generating revenue in minutes – no code required.",
    link_text: "Explore no-code",
    link_url: "#",
  },
];
